
version: '3.9'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - ./srv:/srv
      - ./filebrowser.db:/database/filebrowser.db
      - ./filebrowser.json:/.filebrowser.json
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8095:80
