version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: 'zookeeper'
    networks:
      - local-net
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: 'kafka'
    networks:
      - local-net
    depends_on:
      - zookeeper
    expose:
      - '9092'
      - '29092'
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    volumes:
      - './kafka_data:/data'

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: 'kafdrop'
    networks:
      - local-net
    depends_on:
      - kafka
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: ${KAFKA_BROKERCONNECT}

networks:
  local-net:
    name: local-net