
version: '3.9'
services:
  mariadb:
    image: 'mariadb:latest'
    container_name: 'mariadb'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - './docker-volumes/mariadb:/var/lib/mysql'
    networks:
      - local-net

networks:
  local-net:
    name: local-net
