version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - local-net

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - '${PMA_PORT}:80'
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - local-net

networks:
  local-net:
    name: local-net
